server:
  servlet:
    context-path: /api/users-management

health:
  config:
    enabled: false

# ===============================
# = DATABASE Stuff
# ===============================
spring:
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    contexts: dev
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
  logging:
    level:
      org.hibernate: DEBUG
      org.hibernate.SQL: DEBUG
