server:
  port: 9761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
  file: logs/eureka.log


